// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: microServiceMsg.proto

package microService

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MicroServiceMsgHandlerClient is the client API for MicroServiceMsgHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MicroServiceMsgHandlerClient interface {
	Send(ctx context.Context, in *MicroServiceMsgRequest, opts ...grpc.CallOption) (*MicroServiceMsgResponse, error)
}

type microServiceMsgHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewMicroServiceMsgHandlerClient(cc grpc.ClientConnInterface) MicroServiceMsgHandlerClient {
	return &microServiceMsgHandlerClient{cc}
}

func (c *microServiceMsgHandlerClient) Send(ctx context.Context, in *MicroServiceMsgRequest, opts ...grpc.CallOption) (*MicroServiceMsgResponse, error) {
	out := new(MicroServiceMsgResponse)
	err := c.cc.Invoke(ctx, "/MicroServiceMsgHandler/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MicroServiceMsgHandlerServer is the server API for MicroServiceMsgHandler service.
// All implementations must embed UnimplementedMicroServiceMsgHandlerServer
// for forward compatibility
type MicroServiceMsgHandlerServer interface {
	Send(context.Context, *MicroServiceMsgRequest) (*MicroServiceMsgResponse, error)
	mustEmbedUnimplementedMicroServiceMsgHandlerServer()
}

// UnimplementedMicroServiceMsgHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedMicroServiceMsgHandlerServer struct {
}

func (UnimplementedMicroServiceMsgHandlerServer) Send(context.Context, *MicroServiceMsgRequest) (*MicroServiceMsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedMicroServiceMsgHandlerServer) mustEmbedUnimplementedMicroServiceMsgHandlerServer() {
}

// UnsafeMicroServiceMsgHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MicroServiceMsgHandlerServer will
// result in compilation errors.
type UnsafeMicroServiceMsgHandlerServer interface {
	mustEmbedUnimplementedMicroServiceMsgHandlerServer()
}

func RegisterMicroServiceMsgHandlerServer(s grpc.ServiceRegistrar, srv MicroServiceMsgHandlerServer) {
	s.RegisterService(&MicroServiceMsgHandler_ServiceDesc, srv)
}

func _MicroServiceMsgHandler_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MicroServiceMsgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MicroServiceMsgHandlerServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MicroServiceMsgHandler/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MicroServiceMsgHandlerServer).Send(ctx, req.(*MicroServiceMsgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MicroServiceMsgHandler_ServiceDesc is the grpc.ServiceDesc for MicroServiceMsgHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MicroServiceMsgHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MicroServiceMsgHandler",
	HandlerType: (*MicroServiceMsgHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _MicroServiceMsgHandler_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "microServiceMsg.proto",
}
