package core

// 签名特征
var CTX_SIGNATURE_DATA_KEY = "signatureData"

// 响应方式
var RESPONSE_MODE_HTTP_STATUS = "httpStatus"
var RESPONSE_MODE_ALWAYS200 = "always200"

// 响应Code
var (
	CODE_PARAMS_MISSING       = 10001
	CODE_PARAMS_UNEXPECT      = 10002
	CODE_SIGNATURE_SIG_ERROR  = 20001
	CODE_SIGNATURE_MISSING    = 20002
	CODE_SIGNATURE_PARSE_FAIL = 20003
	CODE_SIGNATURE_EXPIRED    = 20004
	CODE_SIGNATURE_NO_AUTH    = 20005
)

// 响应Code对应文案
var CodeMsgMap map[int]string = map[int]string{
	CODE_PARAMS_MISSING:       "参数缺失",
	CODE_PARAMS_UNEXPECT:      "参数不正确",
	CODE_SIGNATURE_SIG_ERROR:  "签名不正确",
	CODE_SIGNATURE_MISSING:    "签名参数缺失",
	CODE_SIGNATURE_PARSE_FAIL: "签名解析失败或错误",
	CODE_SIGNATURE_EXPIRED:    "签名过期",
	CODE_SIGNATURE_NO_AUTH:    "签名或该用户未授权该功能",
}

// 响应Code对应http status
var CodeStatusMap map[int]int = map[int]int{
	CODE_PARAMS_MISSING:       400,
	CODE_PARAMS_UNEXPECT:      400,
	CODE_SIGNATURE_SIG_ERROR:  400,
	CODE_SIGNATURE_MISSING:    400,
	CODE_SIGNATURE_PARSE_FAIL: 400,
	CODE_SIGNATURE_EXPIRED:    400,
	CODE_SIGNATURE_NO_AUTH:    400,
}
