// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: serviceMsg.proto

package core

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceMsgSenderClient is the client API for ServiceMsgSender service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceMsgSenderClient interface {
	Send(ctx context.Context, in *ServiceMsgRequest, opts ...grpc.CallOption) (*ServiceMsgResponse, error)
}

type serviceMsgSenderClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceMsgSenderClient(cc grpc.ClientConnInterface) ServiceMsgSenderClient {
	return &serviceMsgSenderClient{cc}
}

func (c *serviceMsgSenderClient) Send(ctx context.Context, in *ServiceMsgRequest, opts ...grpc.CallOption) (*ServiceMsgResponse, error) {
	out := new(ServiceMsgResponse)
	err := c.cc.Invoke(ctx, "/ServiceMsgSender/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceMsgSenderServer is the server API for ServiceMsgSender service.
// All implementations must embed UnimplementedServiceMsgSenderServer
// for forward compatibility
type ServiceMsgSenderServer interface {
	Send(context.Context, *ServiceMsgRequest) (*ServiceMsgResponse, error)
	mustEmbedUnimplementedServiceMsgSenderServer()
}

// UnimplementedServiceMsgSenderServer must be embedded to have forward compatible implementations.
type UnimplementedServiceMsgSenderServer struct {
}

func (UnimplementedServiceMsgSenderServer) Send(context.Context, *ServiceMsgRequest) (*ServiceMsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedServiceMsgSenderServer) mustEmbedUnimplementedServiceMsgSenderServer() {}

// UnsafeServiceMsgSenderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceMsgSenderServer will
// result in compilation errors.
type UnsafeServiceMsgSenderServer interface {
	mustEmbedUnimplementedServiceMsgSenderServer()
}

func RegisterServiceMsgSenderServer(s grpc.ServiceRegistrar, srv ServiceMsgSenderServer) {
	s.RegisterService(&ServiceMsgSender_ServiceDesc, srv)
}

func _ServiceMsgSender_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceMsgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceMsgSenderServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ServiceMsgSender/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceMsgSenderServer).Send(ctx, req.(*ServiceMsgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceMsgSender_ServiceDesc is the grpc.ServiceDesc for ServiceMsgSender service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceMsgSender_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ServiceMsgSender",
	HandlerType: (*ServiceMsgSenderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _ServiceMsgSender_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "serviceMsg.proto",
}
