// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: serviceMsg.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceMsgHandlerClient is the client API for ServiceMsgHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceMsgHandlerClient interface {
	Send(ctx context.Context, in *ServiceMsgRequest, opts ...grpc.CallOption) (*ServiceMsgResponse, error)
}

type serviceMsgHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceMsgHandlerClient(cc grpc.ClientConnInterface) ServiceMsgHandlerClient {
	return &serviceMsgHandlerClient{cc}
}

func (c *serviceMsgHandlerClient) Send(ctx context.Context, in *ServiceMsgRequest, opts ...grpc.CallOption) (*ServiceMsgResponse, error) {
	out := new(ServiceMsgResponse)
	err := c.cc.Invoke(ctx, "/ServiceMsgHandler/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceMsgHandlerServer is the server API for ServiceMsgHandler service.
// All implementations must embed UnimplementedServiceMsgHandlerServer
// for forward compatibility
type ServiceMsgHandlerServer interface {
	Send(context.Context, *ServiceMsgRequest) (*ServiceMsgResponse, error)
	mustEmbedUnimplementedServiceMsgHandlerServer()
}

// UnimplementedServiceMsgHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedServiceMsgHandlerServer struct {
}

func (UnimplementedServiceMsgHandlerServer) Send(context.Context, *ServiceMsgRequest) (*ServiceMsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedServiceMsgHandlerServer) mustEmbedUnimplementedServiceMsgHandlerServer() {}

// UnsafeServiceMsgHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceMsgHandlerServer will
// result in compilation errors.
type UnsafeServiceMsgHandlerServer interface {
	mustEmbedUnimplementedServiceMsgHandlerServer()
}

func RegisterServiceMsgHandlerServer(s grpc.ServiceRegistrar, srv ServiceMsgHandlerServer) {
	s.RegisterService(&ServiceMsgHandler_ServiceDesc, srv)
}

func _ServiceMsgHandler_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceMsgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceMsgHandlerServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ServiceMsgHandler/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceMsgHandlerServer).Send(ctx, req.(*ServiceMsgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceMsgHandler_ServiceDesc is the grpc.ServiceDesc for ServiceMsgHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceMsgHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ServiceMsgHandler",
	HandlerType: (*ServiceMsgHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _ServiceMsgHandler_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "serviceMsg.proto",
}
