// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: service.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceHandlerClient is the client API for ServiceHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceHandlerClient interface {
	Request(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error)
	StreamRequest(ctx context.Context, opts ...grpc.CallOption) (ServiceHandler_StreamRequestClient, error)
}

type serviceHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceHandlerClient(cc grpc.ClientConnInterface) ServiceHandlerClient {
	return &serviceHandlerClient{cc}
}

func (c *serviceHandlerClient) Request(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/ServiceHandler/Request", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceHandlerClient) StreamRequest(ctx context.Context, opts ...grpc.CallOption) (ServiceHandler_StreamRequestClient, error) {
	stream, err := c.cc.NewStream(ctx, &ServiceHandler_ServiceDesc.Streams[0], "/ServiceHandler/StreamRequest", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceHandlerStreamRequestClient{stream}
	return x, nil
}

type ServiceHandler_StreamRequestClient interface {
	Send(*ServiceRequest) error
	CloseAndRecv() (*ServiceResponse, error)
	grpc.ClientStream
}

type serviceHandlerStreamRequestClient struct {
	grpc.ClientStream
}

func (x *serviceHandlerStreamRequestClient) Send(m *ServiceRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *serviceHandlerStreamRequestClient) CloseAndRecv() (*ServiceResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ServiceResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServiceHandlerServer is the server API for ServiceHandler service.
// All implementations must embed UnimplementedServiceHandlerServer
// for forward compatibility
type ServiceHandlerServer interface {
	Request(context.Context, *ServiceRequest) (*ServiceResponse, error)
	StreamRequest(ServiceHandler_StreamRequestServer) error
	mustEmbedUnimplementedServiceHandlerServer()
}

// UnimplementedServiceHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedServiceHandlerServer struct {
}

func (UnimplementedServiceHandlerServer) Request(context.Context, *ServiceRequest) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedServiceHandlerServer) StreamRequest(ServiceHandler_StreamRequestServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamRequest not implemented")
}
func (UnimplementedServiceHandlerServer) mustEmbedUnimplementedServiceHandlerServer() {}

// UnsafeServiceHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceHandlerServer will
// result in compilation errors.
type UnsafeServiceHandlerServer interface {
	mustEmbedUnimplementedServiceHandlerServer()
}

func RegisterServiceHandlerServer(s grpc.ServiceRegistrar, srv ServiceHandlerServer) {
	s.RegisterService(&ServiceHandler_ServiceDesc, srv)
}

func _ServiceHandler_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceHandlerServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ServiceHandler/Request",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceHandlerServer).Request(ctx, req.(*ServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceHandler_StreamRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServiceHandlerServer).StreamRequest(&serviceHandlerStreamRequestServer{stream})
}

type ServiceHandler_StreamRequestServer interface {
	SendAndClose(*ServiceResponse) error
	Recv() (*ServiceRequest, error)
	grpc.ServerStream
}

type serviceHandlerStreamRequestServer struct {
	grpc.ServerStream
}

func (x *serviceHandlerStreamRequestServer) SendAndClose(m *ServiceResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *serviceHandlerStreamRequestServer) Recv() (*ServiceRequest, error) {
	m := new(ServiceRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServiceHandler_ServiceDesc is the grpc.ServiceDesc for ServiceHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ServiceHandler",
	HandlerType: (*ServiceHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _ServiceHandler_Request_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamRequest",
			Handler:       _ServiceHandler_StreamRequest_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}
