// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: base.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BaseService_BaseRequest_FullMethodName       = "/BaseService/BaseRequest"
	BaseService_BaseStreamRequest_FullMethodName = "/BaseService/BaseStreamRequest"
)

// BaseServiceClient is the client API for BaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BaseServiceClient interface {
	BaseRequest(ctx context.Context, in *BaseRequestBody, opts ...grpc.CallOption) (*BaseResponseBody, error)
	BaseStreamRequest(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BaseRequestBody, BaseResponseBody], error)
}

type baseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBaseServiceClient(cc grpc.ClientConnInterface) BaseServiceClient {
	return &baseServiceClient{cc}
}

func (c *baseServiceClient) BaseRequest(ctx context.Context, in *BaseRequestBody, opts ...grpc.CallOption) (*BaseResponseBody, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponseBody)
	err := c.cc.Invoke(ctx, BaseService_BaseRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) BaseStreamRequest(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BaseRequestBody, BaseResponseBody], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BaseService_ServiceDesc.Streams[0], BaseService_BaseStreamRequest_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BaseRequestBody, BaseResponseBody]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BaseService_BaseStreamRequestClient = grpc.ClientStreamingClient[BaseRequestBody, BaseResponseBody]

// BaseServiceServer is the server API for BaseService service.
// All implementations must embed UnimplementedBaseServiceServer
// for forward compatibility.
type BaseServiceServer interface {
	BaseRequest(context.Context, *BaseRequestBody) (*BaseResponseBody, error)
	BaseStreamRequest(grpc.ClientStreamingServer[BaseRequestBody, BaseResponseBody]) error
	mustEmbedUnimplementedBaseServiceServer()
}

// UnimplementedBaseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBaseServiceServer struct{}

func (UnimplementedBaseServiceServer) BaseRequest(context.Context, *BaseRequestBody) (*BaseResponseBody, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BaseRequest not implemented")
}
func (UnimplementedBaseServiceServer) BaseStreamRequest(grpc.ClientStreamingServer[BaseRequestBody, BaseResponseBody]) error {
	return status.Errorf(codes.Unimplemented, "method BaseStreamRequest not implemented")
}
func (UnimplementedBaseServiceServer) mustEmbedUnimplementedBaseServiceServer() {}
func (UnimplementedBaseServiceServer) testEmbeddedByValue()                     {}

// UnsafeBaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BaseServiceServer will
// result in compilation errors.
type UnsafeBaseServiceServer interface {
	mustEmbedUnimplementedBaseServiceServer()
}

func RegisterBaseServiceServer(s grpc.ServiceRegistrar, srv BaseServiceServer) {
	// If the following call pancis, it indicates UnimplementedBaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BaseService_ServiceDesc, srv)
}

func _BaseService_BaseRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseRequestBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).BaseRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_BaseRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).BaseRequest(ctx, req.(*BaseRequestBody))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_BaseStreamRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BaseServiceServer).BaseStreamRequest(&grpc.GenericServerStream[BaseRequestBody, BaseResponseBody]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BaseService_BaseStreamRequestServer = grpc.ClientStreamingServer[BaseRequestBody, BaseResponseBody]

// BaseService_ServiceDesc is the grpc.ServiceDesc for BaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BaseService",
	HandlerType: (*BaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BaseRequest",
			Handler:    _BaseService_BaseRequest_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BaseStreamRequest",
			Handler:       _BaseService_BaseStreamRequest_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "base.proto",
}
