// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: intercom.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntercomRequestBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action string `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Data   []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *IntercomRequestBody) Reset() {
	*x = IntercomRequestBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_intercom_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntercomRequestBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntercomRequestBody) ProtoMessage() {}

func (x *IntercomRequestBody) ProtoReflect() protoreflect.Message {
	mi := &file_intercom_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntercomRequestBody.ProtoReflect.Descriptor instead.
func (*IntercomRequestBody) Descriptor() ([]byte, []int) {
	return file_intercom_proto_rawDescGZIP(), []int{0}
}

func (x *IntercomRequestBody) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *IntercomRequestBody) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type IntercomResponseBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Code int64  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *IntercomResponseBody) Reset() {
	*x = IntercomResponseBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_intercom_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntercomResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntercomResponseBody) ProtoMessage() {}

func (x *IntercomResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_intercom_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntercomResponseBody.ProtoReflect.Descriptor instead.
func (*IntercomResponseBody) Descriptor() ([]byte, []int) {
	return file_intercom_proto_rawDescGZIP(), []int{1}
}

func (x *IntercomResponseBody) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *IntercomResponseBody) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *IntercomResponseBody) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_intercom_proto protoreflect.FileDescriptor

var file_intercom_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x41, 0x0a, 0x13, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x50, 0x0a, 0x14, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x96, 0x01, 0x0a, 0x08, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x63,
	0x6f, 0x6d, 0x12, 0x40, 0x0a, 0x0f, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x63, 0x6f, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x1a, 0x15, 0x2e, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6f,
	0x64, 0x79, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x15, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x63, 0x6f, 0x6d,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x2e,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42,
	0x6f, 0x64, 0x79, 0x1a, 0x15, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x22, 0x00, 0x28, 0x01, 0x42, 0x0d,
	0x5a, 0x0b, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_intercom_proto_rawDescOnce sync.Once
	file_intercom_proto_rawDescData = file_intercom_proto_rawDesc
)

func file_intercom_proto_rawDescGZIP() []byte {
	file_intercom_proto_rawDescOnce.Do(func() {
		file_intercom_proto_rawDescData = protoimpl.X.CompressGZIP(file_intercom_proto_rawDescData)
	})
	return file_intercom_proto_rawDescData
}

var file_intercom_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_intercom_proto_goTypes = []any{
	(*IntercomRequestBody)(nil),  // 0: IntercomRequestBody
	(*IntercomResponseBody)(nil), // 1: IntercomResponseBody
}
var file_intercom_proto_depIdxs = []int32{
	0, // 0: Intercom.IntercomRequest:input_type -> IntercomRequestBody
	0, // 1: Intercom.IntercomStreamRequest:input_type -> IntercomRequestBody
	1, // 2: Intercom.IntercomRequest:output_type -> IntercomResponseBody
	1, // 3: Intercom.IntercomStreamRequest:output_type -> IntercomResponseBody
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_intercom_proto_init() }
func file_intercom_proto_init() {
	if File_intercom_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_intercom_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*IntercomRequestBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_intercom_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*IntercomResponseBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_intercom_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_intercom_proto_goTypes,
		DependencyIndexes: file_intercom_proto_depIdxs,
		MessageInfos:      file_intercom_proto_msgTypes,
	}.Build()
	File_intercom_proto = out.File
	file_intercom_proto_rawDesc = nil
	file_intercom_proto_goTypes = nil
	file_intercom_proto_depIdxs = nil
}
